/**
 * Root folder for every artifact generated by the Snowflake extractor
 * (partitioned JSON files, the xlsx workbook, manifest.json). Centralized
 * here so the output location only needs to change in one place.
 */
export const OUTPUT_DIR = "snowflake-metadata-output";

/**
 * Name of the consolidated xlsx workbook, written inside OUTPUT_DIR.
 */
export const XLSX_FILE_NAME = "snowflake-metadata-results.xlsx";
